<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPUlProm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPUlProm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPUlProm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPUlProm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPUlProm\App_KernelDevDebugContainer([
    'container.build_hash' => 'PUlProm',
    'container.build_id' => '1780bbf8',
    'container.build_time' => 1630584087,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPUlProm');
